# Our primary language is Python.
language: python
python:
  - "2.7"

# We need Java 8 for SHACL testing.
addons:
  apt:
    packages:
      - oracle-java8-set-default

# Install pip requirements.
install: 
  - pip install --upgrade pip
  - pip install -r requirements.txt
  - pip install pytest
  - cd tests/java
  - bash -c "echo \$JAVA_HOME"
  - bash -c "javac -version"
  - bash -c "mvn package"

# Run the py.test suite.
script: py.test tests
