# Our primary language is Python.
language: python
python:
  - "2.7"

# We need Java 8 for SHACL testing.
addons:
  apt:
    packages:
      - oracle-java8-set-default

# Install pip requirements and compile Java code,
# then return to the root directory.
install: 
  - pip install --upgrade pip
  - pip install -r requirements.txt
  - pip install pytest
  - cd tests/java
  - bash -lc "mvn package"
  - jar tf target/testShacl-0.1-SNAPSHOT.jar
  - cd ../..
  - java -version

# Run the py.test suite.
script: py.test tests
