sudo: required
language: java
jdk:
  - oraclejdk8
python:
  - "2.7"
# command to install dependencies
#
# unfortunately needs to be custom because updating setuptools from within
# requirements.txt fails to be seen by the html5lib installation, and the
# version pre-installed on Travis is too low.
install: 
  - sudo mkdir /opt/jena
  - sudo curl "http://mirror.olnevhost.net/pub/apache/jena/binaries/apache-jena-3.1.0.zip" -o /opt/jena/apache-jena-3.1.0.zip
  - sudo unzip "/opt/jena/apache-jena-3.1.0.zip" -d "/opt/jena"
  - export JENAHOME=/opt/jena/apache-jena-3.1.0
  - sudo pip install --upgrade pip
  - sudo pip install -r requirements.txt
  - sudo pip install pytest
# command to run tests
script: py.test tests
