sudo: required
language: java
jdk:
  - oraclejdk8
python:
  - "2.7"
# command to install dependencies
#
# unfortunately needs to be custom because updating setuptools from within
# requirements.txt fails to be seen by the html5lib installation, and the
# version pre-installed on Travis is too low.
install: 
  - sudo pip install --upgrade pip
  - sudo pip install -r requirements.txt
  - sudo pip install pytest
# command to run tests
script: py.test tests
